spring:
  application:
    name: bai3
  ai:
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: ${OPEN_ROUTER_API_KEY}
      chat:
        model: gpt-oss-20b
langfuse:
  public-key: ${LANGFUSE_PUBLIC_KEY:pk-lf-demo}
  secret-key: ${LANGFUSE_SECRET_KEY:sk-lf-demo}
  base-url: ${LANGFUSE_BASE_URL:https://cloud.langfuse.com}
  enabled: true